### ISSUE TITLE
Cannot read metadata of undefined

### ISSUE THREAD

**Issue by mwzhu** [Turk-Mumtaz/nft-sales-bot#2]
Hi I am trying to run your bot on my local machine but get this error:

(base) C02R4002GW6W:nft-sales-bot local$ PROJECT_ADDRESS=EooDxue4oQCschn3U4EkBTcCLz5Mk3YMqx18YWeb6pW7 DISCORD_URL=https://discordapp.com/api/webhooks/924497703629635634/rxYwOwsN8ZR40sOWCPYATy4ih5rT0OoJ13Sio7okdtg9MHA2j7WszSsBOsgcyZG-f9fu node sales_bot.js
/Users/local/Desktop/nft-sales-bot/sales_bot.js:14
const { metadata: { Metadata } } = programs;
                    ^

TypeError: Cannot read property 'Metadata' of undefined
    at Object.<anonymous> (/Users/local/Desktop/nft-sales-bot/sales_bot.js:14:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by nftmogul** [comment]
> Hi I am trying to run your bot on my local machine but get this error:
> 
> (base) C02R4002GW6W:nft-sales-bot local$ PROJECT_ADDRESS=EooDxue4oQCschn3U4EkBTcCLz5Mk3YMqx18YWeb6pW7 DISCORD_URL=https://discordapp.com/api/webhooks/924497703629635634/rxYwOwsN8ZR40sOWCPYATy4ih5rT0OoJ13Sio7okdtg9MHA2j7WszSsBOsgcyZG-f9fu node sales_bot.js /Users/local/Desktop/nft-sales-bot/sales_bot.js:14 const { metadata: { Metadata } } = programs; ^
> 
> TypeError: Cannot read property 'Metadata' of undefined at Object. (/Users/local/Desktop/nft-sales-bot/sales_bot.js:14:21) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47

I am getting the same error as @mwzhu. please advise!

**Comment by Turk-Mumtaz** [comment]
yeah it seems metaplex has changed their API with the new version - should be fixed now
