### ISSUE TITLE
Script stopped after a while on replit

### ISSUE THREAD

**Issue by Mathieuduverney** [Turk-Mumtaz/nft-sales-bot#4]
Hi guys,

I ran the script on replit, but after a while it stopped without showing any issue.

Do you guys have any idea how we could do so it never stops?

Thanks
Mathieu

**Comment by EclipseOfficeTech** [comment]
What log files say? Is it a free account or hacker?

**Comment by Mathieuduverney** [comment]
Logs does not say anything
It just stopped and I'm using free account.

You think it is related?

**Comment by EclipseOfficeTech** [comment]
The free account won’t stay always on you need a hacker paid account for it
to stay always on.

Either get a hacker account or get a cheap vps and run it from there.

**Comment by Turk-Mumtaz** [comment]
=
