### ISSUE TITLE
Adding Twitter Support?

### ISSUE THREAD

**Issue by EclipseOfficeTech** [Turk-Mumtaz/nft-sales-bot#5]
First thanks for the discord bot, its simple and does exactly what we require.

We keep getting asked for a twitter bot also, and as per birth of this project the prices banded about are high.

Is there any chance you plan on bringing in support for twitter posting also?

**Comment by Turk-Mumtaz** [comment]
no immediate plans, but follow @blocksmithlabs on twitter for updates. going to release something soon
